[package]
name = "squad"
version = "0.1.0"
authors = ["Marko Baricevic <marbar3778@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
exclude_entrypoint = []

[dependencies]
solana-sdk = { version = "1.3.14", default-features = false }
spl-token = { version = "=2.0.3", default-features = false }
