[package]
name = "squad"
version = "0.1.0"
authors = ["Marko Baricevic <marbar3778@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
exclude_entrypoint = []

[dependencies]
solana-program = "1.4.4"
spl-token = "=2.0.8"
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.1"
serde = "1.0.117"
serde_derive = "1.0.103"
thiserror = "1.0"

[dev-dependencies]
solana-sdk = "1.4.4"
